// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIdp6u9-SFdDiqn0qP_DOtBOnqlgpCBdU',
    appId: '1:966622088956:web:cbdfb147c3c0ab56f6d179',
    messagingSenderId: '966622088956',
    projectId: 'brainplus-bd',
    authDomain: 'brainplus-bd.firebaseapp.com',
    storageBucket: 'brainplus-bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEoX27mc7pFJ89JFOklPHEMZO-ZxLqvH8',
    appId: '1:966622088956:android:7989eeff716a655df6d179',
    messagingSenderId: '966622088956',
    projectId: 'brainplus-bd',
    storageBucket: 'brainplus-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGuWpnaEMm4oGdk5-X6mmOqttT7Vex24',
    appId: '1:966622088956:ios:50f60cf5a725d260f6d179',
    messagingSenderId: '966622088956',
    projectId: 'brainplus-bd',
    storageBucket: 'brainplus-bd.firebasestorage.app',
    iosBundleId: 'com.example.resapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYGuWpnaEMm4oGdk5-X6mmOqttT7Vex24',
    appId: '1:966622088956:ios:50f60cf5a725d260f6d179',
    messagingSenderId: '966622088956',
    projectId: 'brainplus-bd',
    storageBucket: 'brainplus-bd.firebasestorage.app',
    iosBundleId: 'com.example.resapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIdp6u9-SFdDiqn0qP_DOtBOnqlgpCBdU',
    appId: '1:966622088956:web:12d4207ffb04604cf6d179',
    messagingSenderId: '966622088956',
    projectId: 'brainplus-bd',
    authDomain: 'brainplus-bd.firebaseapp.com',
    storageBucket: 'brainplus-bd.firebasestorage.app',
  );
}
